[workspace]
authors = ["Dishika Taneja"]
channels = ["conda-forge"]
name = "analysis-dishika"
platforms = ["linux-64"]

[tasks]

[dependencies]
arrow = "*"
bottleneck = "*"
cartopy = "*"
cliff = "*"
cmocean = "*"
coverage = "*"
dask = "*"
erddapy = "*"
f90nml = "*"
gsw = "*"
ipdb = "*"
ipython = "*"
jupyterlab = "*"
lxml = "*"
matplotlib = "*"
nbsphinx = "*"
netcdf4 = "*"
numpy = ">=2.4.6,<3"
openpyxl = "*"
pandas = "*"
pillow = "*"
pip = "*"
pyproj = "*"
pytest = "*"
python = "3.14.*"
pytz = "*"
python-dateutil = "*"
pyyaml = "*"
requests = "*"
retrying = "*"
scipy = "*"
shapely = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
tqdm = "*"
xarray = ">=2026.4.0,<2027"
scikit-learn = ">=1.8.0,<2"

[pypi-dependencies]
angles = "*"
salishseatools = { git = "https://github.com/SalishSeaCast/tools.git", subdirectory = "SalishSeaTools" }

